/**
 * STATUS & CONTROL (debuff on enemies) modules
 * Slot Type: C (Control)
 *
 * Best on Tesla and Laser turrets.
 */
import { ModuleDef } from './types';

export const CONTROL: ModuleDef[] = [
  {
    id: 'c_slow',
    name: 'Cryo Rounds',
    icon: '🌨️',
    category: 'Status – Control',
    slotType: 'C',
    rarity: 'common',
    baseCost: 80,
    costPerLevel: 40,
    maxLevel: 10,
    description: 'Slows enemy movement speed on hit',
    statKey: 'slow_amount',
    baseValue: 5,
    unit: '%',
    applicableTo: ['tesla', 'laser', 'cannon'],
  },
  {
    id: 'c_stun',
    name: 'Shock Capacitor',
    icon: '⚡',
    category: 'Status – Control',
    slotType: 'C',
    rarity: 'rare',
    baseCost: 200,
    costPerLevel: 100,
    maxLevel: 6,
    description: 'Chance to stun enemies briefly',
    statKey: 'stun_chance',
    baseValue: 4,
    unit: '%',
    applicableTo: ['tesla', 'cannon'],
  },
  {
    id: 'c_freeze',
    name: 'Absolute Zero',
    icon: '🧊',
    category: 'Status – Control',
    slotType: 'C',
    rarity: 'epic',
    baseCost: 500,
    costPerLevel: 250,
    maxLevel: 5,
    description: 'Builds freeze stacks; enemies fully freeze at max',
    statKey: 'freeze_build',
    baseValue: 8,
    unit: 'stacks',
    applicableTo: ['tesla', 'laser'],
  },
  {
    id: 'c_knockback',
    name: 'Concussive Core',
    icon: '💨',
    category: 'Status – Control',
    slotType: 'C',
    rarity: 'rare',
    baseCost: 200,
    costPerLevel: 100,
    maxLevel: 6,
    description: 'Knockback pushes enemies back on hit',
    statKey: 'knockback',
    baseValue: 10,
    unit: 'px',
    applicableTo: ['cannon', 'missile'],
  },
  {
    id: 'c_weaken',
    name: 'Neuro-Toxin',
    icon: '🧪',
    category: 'Status – Control',
    slotType: 'C',
    rarity: 'rare',
    baseCost: 200,
    costPerLevel: 100,
    maxLevel: 6,
    description: 'Weakened enemies deal less damage',
    statKey: 'weaken_amount',
    baseValue: 5,
    unit: '%',
    applicableTo: ['laser', 'tesla'],
  },
  {
    id: 'c_mark',
    name: 'Target Painter',
    icon: '🎯',
    category: 'Status – Control',
    slotType: 'C',
    rarity: 'epic',
    baseCost: 500,
    costPerLevel: 250,
    maxLevel: 5,
    description: 'Marked targets take increased damage from all sources',
    statKey: 'mark_bonus',
    baseValue: 10,
    unit: '%',
    applicableTo: ['laser', 'tesla', 'cannon'],
  },
  {
    id: 'c_pull',
    name: 'Gravity Well',
    icon: '🌀',
    category: 'Status – Control',
    slotType: 'C',
    rarity: 'legendary',
    baseCost: 1200,
    costPerLevel: 600,
    maxLevel: 4,
    description: 'Pulls nearby enemies toward target on hit',
    statKey: 'pull_radius',
    baseValue: 30,
    unit: 'px',
    applicableTo: ['tesla', 'missile'],
  },
  {
    id: 'c_chain_lightning',
    name: 'Arc Chain',
    icon: '⚡',
    category: 'Status – Control',
    slotType: 'C',
    rarity: 'epic',
    baseCost: 500,
    costPerLevel: 250,
    maxLevel: 5,
    description: 'Lightning chains to nearby enemies after hitting',
    statKey: 'chain_count',
    baseValue: 1,
    unit: 'targets',
    applicableTo: ['tesla'],
  },
];
