/**
 * DEFENSIVE modules
 * Slot Type: O (Omni – defensive fits in utility slots)
 *
 * Player-focused. Turrets can use some (hp/shield variants).
 */
import { ModuleDef } from './types';

export const DEFENSIVE: ModuleDef[] = [
  {
    id: 'o_max_hp',
    name: 'Nanoskin Plating',
    icon: '🛡️',
    category: 'Defensive',
    slotType: 'O',
    rarity: 'common',
    baseCost: 80,
    costPerLevel: 40,
    maxLevel: 10,
    description: 'Increases maximum HP',
    statKey: 'max_hp',
    baseValue: 10,
    unit: 'hp',
    applicableTo: 'player',
  },
  {
    id: 'o_hp_regen',
    name: 'Bio-Regenerator',
    icon: '❤️',
    category: 'Defensive',
    slotType: 'O',
    rarity: 'rare',
    baseCost: 200,
    costPerLevel: 100,
    maxLevel: 6,
    description: 'Slowly regenerates HP during combat',
    statKey: 'hp_regen',
    baseValue: 1,
    unit: 'hp/s',
    applicableTo: 'player',
  },
  {
    id: 'o_shield',
    name: 'Void Shield',
    icon: '💠',
    category: 'Defensive',
    slotType: 'O',
    rarity: 'epic',
    baseCost: 500,
    costPerLevel: 250,
    maxLevel: 5,
    description: 'Adds a rechargeable overshield layer',
    statKey: 'shield',
    baseValue: 15,
    unit: 'hp',
    applicableTo: 'player',
  },
  {
    id: 'o_dmg_resist',
    name: 'Reactive Alloy',
    icon: '🔩',
    category: 'Defensive',
    slotType: 'O',
    rarity: 'rare',
    baseCost: 200,
    costPerLevel: 100,
    maxLevel: 8,
    description: 'Flat damage reduction per hit',
    statKey: 'dmg_resist',
    baseValue: 3,
    unit: '%',
    applicableTo: 'player',
  },
  {
    id: 'o_dodge',
    name: 'Phase Step',
    icon: '👻',
    category: 'Defensive',
    slotType: 'O',
    rarity: 'epic',
    baseCost: 500,
    costPerLevel: 250,
    maxLevel: 5,
    description: 'Chance to dodge incoming attacks',
    statKey: 'dodge_chance',
    baseValue: 4,
    unit: '%',
    applicableTo: 'player',
  },
  {
    id: 'o_thorns',
    name: 'Spike Shell',
    icon: '🦔',
    category: 'Defensive',
    slotType: 'O',
    rarity: 'rare',
    baseCost: 200,
    costPerLevel: 100,
    maxLevel: 6,
    description: 'Reflects a portion of damage back to attackers',
    statKey: 'thorns',
    baseValue: 5,
    unit: '%',
    applicableTo: 'player',
  },
  {
    id: 'o_second_wind',
    name: 'Last Stand',
    icon: '🌟',
    category: 'Defensive',
    slotType: 'O',
    rarity: 'legendary',
    baseCost: 1200,
    costPerLevel: 600,
    maxLevel: 3,
    description: 'Once per run: survive a killing blow with 1 HP',
    statKey: 'second_wind',
    baseValue: 1,
    unit: 'use',
    applicableTo: 'player',
  },
  {
    id: 'o_invuln_window',
    name: 'Chrono Shell',
    icon: '⏱️',
    category: 'Defensive',
    slotType: 'O',
    rarity: 'epic',
    baseCost: 500,
    costPerLevel: 250,
    maxLevel: 5,
    description: 'Brief invulnerability window after taking damage',
    statKey: 'invuln_frames',
    baseValue: 15,
    unit: 'frames',
    applicableTo: 'player',
  },
  {
    id: 'o_turret_armor',
    name: 'Reinforced Chassis',
    icon: '🏗️',
    category: 'Defensive',
    slotType: 'O',
    rarity: 'common',
    baseCost: 80,
    costPerLevel: 40,
    maxLevel: 10,
    description: 'Increases turret durability / uptime',
    statKey: 'turret_hp_mult',
    baseValue: 8,
    unit: '%',
    applicableTo: ['cannon', 'laser', 'missile', 'tesla'],
  },
];
