/**
 * EXOTIC / BUILD-DEFINING modules
 * Slot Type: E (Exotic)
 *
 * Powerful build-altering effects. Max 1 per turret (enforced in UI).
 * Only epic/legendary rarity.
 */
import { ModuleDef } from './types';

export const EXOTIC: ModuleDef[] = [
  {
    id: 'e_split_shot',
    name: 'Prism Core',
    icon: '🔮',
    category: 'Exotic',
    slotType: 'E',
    rarity: 'legendary',
    baseCost: 1200,
    costPerLevel: 600,
    maxLevel: 3,
    description: 'Bullets split into 3 on impact',
    statKey: 'split_count',
    baseValue: 3,
    unit: 'shards',
    applicableTo: ['cannon', 'missile'],
  },
  {
    id: 'e_chain_bullets',
    name: 'Arc Conductor',
    icon: '⛓️',
    category: 'Exotic',
    slotType: 'E',
    rarity: 'legendary',
    baseCost: 1200,
    costPerLevel: 600,
    maxLevel: 3,
    description: 'Bullets chain to nearby enemies after each hit',
    statKey: 'chain_targets',
    baseValue: 2,
    unit: 'targets',
    applicableTo: ['laser', 'tesla'],
  },
  {
    id: 'e_overkill',
    name: 'Overkill Transfer',
    icon: '☄️',
    category: 'Exotic',
    slotType: 'E',
    rarity: 'epic',
    baseCost: 500,
    costPerLevel: 250,
    maxLevel: 5,
    description: 'Excess damage from a kill carries to the next enemy',
    statKey: 'overkill_carry',
    baseValue: 25,
    unit: '%',
    applicableTo: 'all',
  },
  {
    id: 'e_time_slow',
    name: 'Temporal Rift',
    icon: '⏳',
    category: 'Exotic',
    slotType: 'E',
    rarity: 'legendary',
    baseCost: 1200,
    costPerLevel: 600,
    maxLevel: 3,
    description: 'Briefly slows time around enemies on kill',
    statKey: 'time_slow_dur',
    baseValue: 30,
    unit: 'frames',
    applicableTo: ['tesla', 'laser'],
  },
  {
    id: 'e_type_convert',
    name: 'Element Converter',
    icon: '🔀',
    category: 'Exotic',
    slotType: 'E',
    rarity: 'legendary',
    baseCost: 1200,
    costPerLevel: 600,
    maxLevel: 3,
    description: 'Converts damage type (e.g. fire → poison) each reload',
    statKey: 'dmg_type_convert',
    baseValue: 1,
    unit: 'cycle',
    applicableTo: ['cannon', 'missile'],
  },
  {
    id: 'e_glass_cannon',
    name: 'Glass Cannon Protocol',
    icon: '💀',
    category: 'Exotic',
    slotType: 'E',
    rarity: 'epic',
    baseCost: 500,
    costPerLevel: 250,
    maxLevel: 5,
    description: 'Sacrifice defense for massive damage output',
    statKey: 'glass_cannon',
    baseValue: 15,
    unit: '%',
    applicableTo: 'all',
  },
  {
    id: 'e_ammo_cycle',
    name: 'Elemental Rotator',
    icon: '🔁',
    category: 'Exotic',
    slotType: 'E',
    rarity: 'epic',
    baseCost: 500,
    costPerLevel: 250,
    maxLevel: 4,
    description: 'Cycles between different ammo types on each reload',
    statKey: 'ammo_cycle_bonus',
    baseValue: 10,
    unit: '%',
    applicableTo: ['cannon', 'missile'],
  },
  {
    id: 'e_turret_deploy',
    name: 'Micro-Drone Array',
    icon: '🤖',
    category: 'Exotic',
    slotType: 'E',
    rarity: 'legendary',
    baseCost: 1200,
    costPerLevel: 600,
    maxLevel: 3,
    description: 'Deploys a mini-drone that auto-attacks nearby enemies',
    statKey: 'drone_damage',
    baseValue: 8,
    unit: 'dmg',
    applicableTo: 'player',
  },
];
