/**
 * OFFENSIVE – SPEED & RATE modules
 * Slot Type: V (Velocity)
 *
 * To add a new module: copy an entry, give a unique id,
 * set applicableTo: 'all' | 'player' | TurretType[]
 */
import { ModuleDef } from './types';

export const OFFENSIVE_SPEED: ModuleDef[] = [
  {
    id: 'v_fire_rate',
    name: 'Overclock Trigger',
    icon: '⚡',
    category: 'Offensive – Speed',
    slotType: 'V',
    rarity: 'common',
    baseCost: 80,
    costPerLevel: 40,
    maxLevel: 10,
    description: 'Increases fire rate',
    statKey: 'fire_rate',
    baseValue: 6,
    unit: '%',
    applicableTo: 'all',
  },
  {
    id: 'v_reload',
    name: 'Speed Loader',
    icon: '🔄',
    category: 'Offensive – Speed',
    slotType: 'V',
    rarity: 'common',
    baseCost: 80,
    costPerLevel: 40,
    maxLevel: 10,
    description: 'Reduces reload time between bursts',
    statKey: 'reload_speed',
    baseValue: 8,
    unit: '%',
    applicableTo: ['cannon', 'missile'],
  },
  {
    id: 'v_proj_speed',
    name: 'Accelerator Coil',
    icon: '🚀',
    category: 'Offensive – Speed',
    slotType: 'V',
    rarity: 'common',
    baseCost: 80,
    costPerLevel: 40,
    maxLevel: 10,
    description: 'Faster projectile travel speed',
    statKey: 'bullet_speed',
    baseValue: 7,
    unit: '%',
    applicableTo: 'all',
  },
  {
    id: 'v_multishot',
    name: 'Splitter Array',
    icon: '🔀',
    category: 'Offensive – Speed',
    slotType: 'V',
    rarity: 'epic',
    baseCost: 500,
    costPerLevel: 250,
    maxLevel: 5,
    description: 'Each shot fires extra projectiles',
    statKey: 'extra_projectiles',
    baseValue: 1,
    unit: 'proj',
    applicableTo: ['cannon', 'laser'],
  },
  {
    id: 'v_piercing',
    name: 'Phase Rounds',
    icon: '→→',
    category: 'Offensive – Speed',
    slotType: 'V',
    rarity: 'epic',
    baseCost: 500,
    costPerLevel: 250,
    maxLevel: 4,
    description: 'Shots pierce through enemies',
    statKey: 'pierce_count',
    baseValue: 1,
    unit: 'targets',
    applicableTo: ['laser', 'cannon'],
  },
  {
    id: 'v_ricochet',
    name: 'Ricochet Module',
    icon: '↗️',
    category: 'Offensive – Speed',
    slotType: 'V',
    rarity: 'epic',
    baseCost: 500,
    costPerLevel: 250,
    maxLevel: 4,
    description: 'Bullets bounce to nearby targets',
    statKey: 'ricochet_count',
    baseValue: 1,
    unit: 'bounces',
    applicableTo: ['cannon', 'tesla'],
  },
  {
    id: 'v_homing',
    name: 'Smart Guidance',
    icon: '🎮',
    category: 'Offensive – Speed',
    slotType: 'V',
    rarity: 'rare',
    baseCost: 200,
    costPerLevel: 100,
    maxLevel: 6,
    description: 'Projectiles home in on nearest enemy',
    statKey: 'homing_strength',
    baseValue: 10,
    unit: '%',
    applicableTo: ['missile', 'cannon'],
  },
  {
    id: 'v_burst',
    name: 'Burst Capacitor',
    icon: '💫',
    category: 'Offensive – Speed',
    slotType: 'V',
    rarity: 'rare',
    baseCost: 200,
    costPerLevel: 100,
    maxLevel: 6,
    description: 'Fires in rapid bursts instead of single shots',
    statKey: 'burst_count',
    baseValue: 1,
    unit: 'shots',
    applicableTo: ['cannon', 'laser'],
  },
  {
    id: 'v_cooldown',
    name: 'Thermal Vent',
    icon: '❄️',
    category: 'Offensive – Speed',
    slotType: 'V',
    rarity: 'rare',
    baseCost: 200,
    costPerLevel: 100,
    maxLevel: 8,
    description: 'Reduces ability cooldowns',
    statKey: 'cooldown_reduce',
    baseValue: 5,
    unit: '%',
    applicableTo: ['missile', 'tesla'],
  },
];
