/**
 * OFFENSIVE – DAMAGE modules
 * Slot Type: X (eXplosive/damage)
 *
 * To add a new module: copy an existing entry, give it a unique id,
 * set applicableTo to 'all', 'player', or a TurretType array.
 */
import { ModuleDef } from './types';

export const OFFENSIVE_DAMAGE: ModuleDef[] = [
  {
    id: 'x_base_dmg',
    name: 'Rifling Reinforcement',
    icon: '⚔️',
    category: 'Offensive – Damage',
    slotType: 'X',
    rarity: 'common',
    baseCost: 80,
    costPerLevel: 40,
    maxLevel: 10,
    description: 'Increases base damage output',
    statKey: 'damage',
    baseValue: 8,
    unit: '%',
    applicableTo: 'all',
  },
  {
    id: 'x_poison',
    name: 'Toxic Rounds',
    icon: '☣️',
    category: 'Offensive – Damage',
    slotType: 'X',
    rarity: 'rare',
    baseCost: 200,
    costPerLevel: 100,
    maxLevel: 8,
    description: 'Bullets apply poison (damage over time)',
    statKey: 'poison_dps',
    baseValue: 5,
    unit: 'dps',
    applicableTo: ['cannon', 'laser', 'tesla'],
  },
  {
    id: 'x_burn',
    name: 'Ignite Core',
    icon: '🔥',
    category: 'Offensive – Damage',
    slotType: 'X',
    rarity: 'rare',
    baseCost: 200,
    costPerLevel: 100,
    maxLevel: 8,
    description: 'Chance to ignite enemies on hit',
    statKey: 'burn_chance',
    baseValue: 4,
    unit: '%',
    applicableTo: ['cannon', 'missile'],
  },
  {
    id: 'x_bleed',
    name: 'Serrated Tip',
    icon: '🩸',
    category: 'Offensive – Damage',
    slotType: 'X',
    rarity: 'rare',
    baseCost: 200,
    costPerLevel: 100,
    maxLevel: 8,
    description: 'Physical hits cause bleed damage',
    statKey: 'bleed_dps',
    baseValue: 6,
    unit: 'dps',
    applicableTo: ['cannon', 'missile'],
  },
  {
    id: 'x_explosive',
    name: 'Explosive Payload',
    icon: '💥',
    category: 'Offensive – Damage',
    slotType: 'X',
    rarity: 'epic',
    baseCost: 500,
    costPerLevel: 250,
    maxLevel: 6,
    description: 'Bullets explode on impact (AoE)',
    statKey: 'aoe_radius',
    baseValue: 10,
    unit: 'px',
    applicableTo: ['cannon', 'missile'],
  },
  {
    id: 'x_armor_pierce',
    name: 'Void Piercer',
    icon: '🗡️',
    category: 'Offensive – Damage',
    slotType: 'X',
    rarity: 'epic',
    baseCost: 500,
    costPerLevel: 250,
    maxLevel: 6,
    description: 'Ignores a portion of enemy armor',
    statKey: 'armor_pierce',
    baseValue: 10,
    unit: '%',
    applicableTo: 'all',
  },
  {
    id: 'x_crit_chance',
    name: 'Crit Matrix',
    icon: '🎯',
    category: 'Offensive – Damage',
    slotType: 'X',
    rarity: 'rare',
    baseCost: 200,
    costPerLevel: 100,
    maxLevel: 8,
    description: 'Increases critical hit chance',
    statKey: 'crit_chance',
    baseValue: 3,
    unit: '%',
    applicableTo: 'all',
  },
  {
    id: 'x_crit_dmg',
    name: 'Glass Spike',
    icon: '💎',
    category: 'Offensive – Damage',
    slotType: 'X',
    rarity: 'epic',
    baseCost: 500,
    costPerLevel: 250,
    maxLevel: 6,
    description: 'Critical hits deal massively more damage',
    statKey: 'crit_damage',
    baseValue: 15,
    unit: '%',
    applicableTo: 'all',
  },
  {
    id: 'x_execute',
    name: 'Finisher Protocol',
    icon: '💀',
    category: 'Offensive – Damage',
    slotType: 'X',
    rarity: 'epic',
    baseCost: 500,
    costPerLevel: 250,
    maxLevel: 5,
    description: 'Bonus damage vs enemies below 25% HP',
    statKey: 'execute_bonus',
    baseValue: 20,
    unit: '%',
    applicableTo: 'all',
  },
  {
    id: 'x_dmg_ramp',
    name: 'Sustained Fire',
    icon: '📈',
    category: 'Offensive – Damage',
    slotType: 'X',
    rarity: 'rare',
    baseCost: 200,
    costPerLevel: 100,
    maxLevel: 8,
    description: 'Damage increases the longer you fire',
    statKey: 'ramp_dmg',
    baseValue: 2,
    unit: '%/s',
    applicableTo: ['laser', 'cannon'],
  },
  {
    id: 'x_vs_shields',
    name: 'Shield Breaker',
    icon: '🔱',
    category: 'Offensive – Damage',
    slotType: 'X',
    rarity: 'legendary',
    baseCost: 1200,
    costPerLevel: 600,
    maxLevel: 5,
    description: 'Massive bonus damage vs shielded enemies',
    statKey: 'shield_bonus',
    baseValue: 25,
    unit: '%',
    applicableTo: ['cannon', 'missile', 'tesla'],
  },
];
