/**
 * PASSIVE / SCALING modules
 * Slot Type: O (Omni – fits utility slots)
 *
 * Global passive bonuses that scale the longer a run goes.
 */
import { ModuleDef } from './types';

export const PASSIVE: ModuleDef[] = [
  {
    id: 'o_kill_stack',
    name: 'Kill Counter',
    icon: '💠',
    category: 'Passive – Scaling',
    slotType: 'O',
    rarity: 'rare',
    baseCost: 200,
    costPerLevel: 100,
    maxLevel: 8,
    description: 'Damage stacks higher with each kill (resets on death)',
    statKey: 'kill_stack_dmg',
    baseValue: 0.5,
    unit: '%/kill',
    applicableTo: 'all',
  },
  {
    id: 'o_lifesteal',
    name: 'Vampiric Edge',
    icon: '🧛',
    category: 'Passive – Scaling',
    slotType: 'O',
    rarity: 'epic',
    baseCost: 500,
    costPerLevel: 250,
    maxLevel: 5,
    description: 'Restore HP equal to a % of damage dealt',
    statKey: 'lifesteal',
    baseValue: 2,
    unit: '%',
    applicableTo: 'player',
  },
  {
    id: 'o_dmg_missing_hp',
    name: 'Desperation Drive',
    icon: '📉',
    category: 'Passive – Scaling',
    slotType: 'O',
    rarity: 'epic',
    baseCost: 500,
    costPerLevel: 250,
    maxLevel: 5,
    description: 'Damage increases as your HP gets lower',
    statKey: 'low_hp_dmg',
    baseValue: 5,
    unit: '%',
    applicableTo: 'player',
  },
  {
    id: 'o_gold_gain',
    name: 'Salvage Protocol',
    icon: '💰',
    category: 'Passive – Scaling',
    slotType: 'O',
    rarity: 'rare',
    baseCost: 200,
    costPerLevel: 100,
    maxLevel: 8,
    description: 'Increases gold earned from kills',
    statKey: 'gold_gain',
    baseValue: 5,
    unit: '%',
    applicableTo: 'player',
  },
  {
    id: 'o_xp_gain',
    name: 'Neural Tap',
    icon: '🧠',
    category: 'Passive – Scaling',
    slotType: 'O',
    rarity: 'rare',
    baseCost: 200,
    costPerLevel: 100,
    maxLevel: 8,
    description: 'Increases XP earned from kills',
    statKey: 'xp_gain',
    baseValue: 8,
    unit: '%',
    applicableTo: 'player',
  },
  {
    id: 'o_luck',
    name: 'Fortune Chip',
    icon: '🍀',
    category: 'Passive – Scaling',
    slotType: 'O',
    rarity: 'rare',
    baseCost: 200,
    costPerLevel: 100,
    maxLevel: 6,
    description: 'Improves loot drop quality and rates',
    statKey: 'luck',
    baseValue: 5,
    unit: '%',
    applicableTo: 'player',
  },
  {
    id: 'o_dmg_speed',
    name: 'Kinetic Surge',
    icon: '⚡',
    category: 'Passive – Scaling',
    slotType: 'O',
    rarity: 'legendary',
    baseCost: 1200,
    costPerLevel: 600,
    maxLevel: 4,
    description: 'Damage scales with bullet travel speed',
    statKey: 'speed_dmg_scale',
    baseValue: 0.1,
    unit: 'dmg/spd',
    applicableTo: ['cannon', 'missile', 'laser'],
  },
];
