/**
 * UTILITY – AMMO & RESOURCES modules
 * Slot Type: O (Omni/utility)
 *
 * To add a new module: copy an entry, give a unique id,
 * set applicableTo: 'all' | 'player' | TurretType[]
 */
import { ModuleDef } from './types';

export const UTILITY: ModuleDef[] = [
  {
    id: 'o_magazine',
    name: 'Extended Mag',
    icon: '🔋',
    category: 'Utility – Ammo',
    slotType: 'O',
    rarity: 'common',
    baseCost: 80,
    costPerLevel: 40,
    maxLevel: 10,
    description: 'Larger magazine – fire longer before reload',
    statKey: 'magazine',
    baseValue: 5,
    unit: 'rounds',
    applicableTo: ['cannon', 'laser', 'missile'],
  },
  {
    id: 'o_ammo_regen',
    name: 'Ammo Fabricator',
    icon: '♻️',
    category: 'Utility – Ammo',
    slotType: 'O',
    rarity: 'rare',
    baseCost: 200,
    costPerLevel: 100,
    maxLevel: 6,
    description: 'Passively regenerates ammo over time',
    statKey: 'ammo_regen',
    baseValue: 1,
    unit: '/s',
    applicableTo: ['cannon', 'laser'],
  },
  {
    id: 'o_free_shot',
    name: 'Zero-Cost Chamber',
    icon: '🎁',
    category: 'Utility – Ammo',
    slotType: 'O',
    rarity: 'epic',
    baseCost: 500,
    costPerLevel: 250,
    maxLevel: 5,
    description: 'Chance per shot to not consume ammo',
    statKey: 'free_shot_chance',
    baseValue: 5,
    unit: '%',
    applicableTo: ['cannon', 'missile'],
  },
  {
    id: 'o_energy_cost',
    name: 'Flux Reducer',
    icon: '⚙️',
    category: 'Utility – Ammo',
    slotType: 'O',
    rarity: 'rare',
    baseCost: 200,
    costPerLevel: 100,
    maxLevel: 8,
    description: 'Reduces energy cost per shot',
    statKey: 'energy_cost_reduce',
    baseValue: 5,
    unit: '%',
    applicableTo: ['laser', 'tesla'],
  },
  {
    id: 'o_overheat',
    name: 'Thermal Shielding',
    icon: '🌡️',
    category: 'Utility – Ammo',
    slotType: 'O',
    rarity: 'rare',
    baseCost: 200,
    costPerLevel: 100,
    maxLevel: 6,
    description: 'Raises overheat threshold',
    statKey: 'overheat_threshold',
    baseValue: 10,
    unit: '%',
    applicableTo: ['laser', 'cannon'],
  },
  {
    id: 'o_cooling',
    name: 'Cryo Coolant',
    icon: '🧊',
    category: 'Utility – Ammo',
    slotType: 'O',
    rarity: 'rare',
    baseCost: 200,
    costPerLevel: 100,
    maxLevel: 6,
    description: 'Improves cooling rate when not firing',
    statKey: 'cooling_rate',
    baseValue: 10,
    unit: '%',
    applicableTo: ['laser', 'cannon'],
  },
  {
    id: 'o_range',
    name: 'Sensor Array',
    icon: '📡',
    category: 'Utility – Ammo',
    slotType: 'O',
    rarity: 'common',
    baseCost: 80,
    costPerLevel: 40,
    maxLevel: 10,
    description: 'Increases detection and targeting range',
    statKey: 'range',
    baseValue: 20,
    unit: 'px',
    applicableTo: 'all',
  },
];
