/** BOSS-CLASS ENEMIES — rare, massive HP, appear on milestone waves */
import { EnemyDef } from './types';

export const BOSSES: EnemyDef[] = [
  {
    id: 'elite',
    name: 'Elite Commander',
    icon: '⭐',
    category: 'boss',
    baseHp: 450,
    hpPerWave: 90,
    speed: 1.0,
    speedPerWave: 0.03,
    armor: 12,
    size: 60,
    weakTo: { electric: 1.4, explosive: 1.3 },
    strongAgainst: { physical: 0.65, poison: 0.6 },
    goldReward: 80,
    xpReward: 180,
    turretXpReward: 45,
    materialDropChance: 0.9,
    spawnCount: 1,
    spawnYOffset: 0,
    color: '#1e3a5f',
    borderColor: '#60a5fa',
    baseDamage: 40,
    isBoss: true,
  },
  {
    id: 'void_lord',
    name: 'Void Lord',
    icon: '👁️',
    category: 'boss',
    baseHp: 900,
    hpPerWave: 160,
    speed: 0.7,
    speedPerWave: 0.02,
    armor: 22,
    size: 74,
    weakTo: { laser: 1.5, fire: 1.3 },
    strongAgainst: { physical: 0.4, electric: 0.5, explosive: 0.6, ice: 0.7 },
    goldReward: 150,
    xpReward: 350,
    turretXpReward: 90,
    materialDropChance: 1.0,
    spawnCount: 1,
    spawnYOffset: 0,
    color: '#0d0d24',
    borderColor: '#818cf8',
    baseDamage: 70,
    isBoss: true,
  },
  {
    id: 'corrupted_titan',
    name: 'Corrupted Titan',
    icon: '💀',
    category: 'boss',
    baseHp: 1600,
    hpPerWave: 280,
    speed: 0.5,
    speedPerWave: 0.01,
    armor: 30,
    size: 84,
    weakTo: { explosive: 1.8, electric: 1.6 },
    strongAgainst: { physical: 0.3, laser: 0.5, poison: 0.4, fire: 0.5, ice: 0.5 },
    goldReward: 280,
    xpReward: 640,
    turretXpReward: 160,
    materialDropChance: 1.0,
    spawnCount: 1,
    spawnYOffset: 0,
    color: '#1c0a0a',
    borderColor: '#dc2626',
    baseDamage: 100,
    isBoss: true,
  },
];
