/** HEAVY-CLASS ENEMIES — slow, high HP, heavy armour */
import { EnemyDef } from './types';

export const HEAVY: EnemyDef[] = [
  {
    id: 'tank',
    name: 'Siege Tank',
    icon: '🛡️',
    category: 'heavy',
    baseHp: 280,
    hpPerWave: 40,
    speed: 0.6,
    speedPerWave: 0.02,
    armor: 8,
    size: 54,
    weakTo: { electric: 1.4, explosive: 1.5 },
    strongAgainst: { physical: 0.6, poison: 0.5 },
    goldReward: 35,
    xpReward: 80,
    turretXpReward: 20,
    materialDropChance: 0.45,
    spawnCount: 1,
    spawnYOffset: 0,
    color: '#7c2d12',
    borderColor: '#f97316',
    baseDamage: 30,
  },
  {
    id: 'juggernaut',
    name: 'Juggernaut',
    icon: '⚙️',
    category: 'heavy',
    baseHp: 500,
    hpPerWave: 70,
    speed: 0.4,
    speedPerWave: 0.01,
    armor: 18,
    size: 66,
    weakTo: { electric: 1.6, laser: 1.3 },
    strongAgainst: { physical: 0.4, explosive: 0.6, fire: 0.7 },
    goldReward: 60,
    xpReward: 140,
    turretXpReward: 35,
    materialDropChance: 0.65,
    spawnCount: 1,
    spawnYOffset: 0,
    color: '#1c1917',
    borderColor: '#78716c',
    baseDamage: 50,
  },
  {
    id: 'shielder',
    name: 'Void Shielder',
    icon: '🔋',
    category: 'heavy',
    baseHp: 180,
    hpPerWave: 25,
    speed: 0.9,
    speedPerWave: 0.03,
    armor: 5,
    size: 48,
    weakTo: { electric: 1.8, laser: 1.5 },
    strongAgainst: { physical: 0.5, explosive: 0.5, fire: 0.6, ice: 0.7 },
    goldReward: 28,
    xpReward: 65,
    turretXpReward: 16,
    materialDropChance: 0.4,
    spawnCount: 1,
    spawnYOffset: 0,
    color: '#0c4a6e',
    borderColor: '#38bdf8',
    baseDamage: 22,
  },
];
