/** SCOUT-CLASS ENEMIES — fast, low HP, light armour */
import { EnemyDef } from './types';

export const SCOUTS: EnemyDef[] = [
  {
    id: 'scout',
    name: 'Scout Drone',
    icon: '👾',
    category: 'scout',
    baseHp: 45,
    hpPerWave: 10,
    speed: 2.0,
    speedPerWave: 0.05,
    armor: 0,
    size: 34,
    weakTo: { physical: 1.3, explosive: 1.2 },
    strongAgainst: { ice: 0.8 },
    goldReward: 6,
    xpReward: 20,
    turretXpReward: 5,
    materialDropChance: 0.15,
    spawnCount: 1,
    spawnYOffset: 0,
    color: '#7f1d1d',
    borderColor: '#ef4444',
    baseDamage: 12,
  },
  {
    id: 'runner',
    name: 'Sprint Runner',
    icon: '💨',
    category: 'scout',
    baseHp: 30,
    hpPerWave: 8,
    speed: 3.5,
    speedPerWave: 0.08,
    armor: 0,
    size: 26,
    weakTo: { electric: 1.5, poison: 1.2 },
    strongAgainst: { physical: 0.75 },
    goldReward: 4,
    xpReward: 14,
    turretXpReward: 3,
    materialDropChance: 0.1,
    spawnCount: 1,
    spawnYOffset: 0,
    color: '#1e1b4b',
    borderColor: '#818cf8',
    baseDamage: 8,
  },
  {
    id: 'glass_cannon',
    name: 'Glass Cannon',
    icon: '🔫',
    category: 'scout',
    baseHp: 20,
    hpPerWave: 5,
    speed: 1.8,
    speedPerWave: 0.04,
    armor: 0,
    size: 28,
    weakTo: { explosive: 1.8, fire: 1.4 },
    strongAgainst: {},
    goldReward: 8,
    xpReward: 22,
    turretXpReward: 6,
    materialDropChance: 0.2,
    spawnCount: 1,
    spawnYOffset: 0,
    color: '#4c1d95',
    borderColor: '#c084fc',
    baseDamage: 20,
  },
];
