/** SWARM-CLASS ENEMIES — many small units, low individual HP */
import { EnemyDef } from './types';

export const SWARM: EnemyDef[] = [
  {
    id: 'swarmer',
    name: 'Nano Swarmer',
    icon: '◆',
    category: 'swarm',
    baseHp: 12,
    hpPerWave: 3,
    speed: 3.8,
    speedPerWave: 0.1,
    armor: 0,
    size: 22,
    weakTo: { explosive: 2.0, fire: 1.6 },
    strongAgainst: { laser: 0.6 },
    goldReward: 3,
    xpReward: 8,
    turretXpReward: 2,
    materialDropChance: 0.08,
    spawnCount: 3,
    spawnYOffset: 38,
    color: '#4c1d95',
    borderColor: '#a855f7',
    baseDamage: 5,
  },
  {
    id: 'bomber_swarm',
    name: 'Bomber Swarm',
    icon: '💥',
    category: 'swarm',
    baseHp: 50,
    hpPerWave: 8,
    speed: 2.2,
    speedPerWave: 0.06,
    armor: 0,
    size: 34,
    weakTo: { physical: 1.4, ice: 1.3 },
    strongAgainst: { fire: 0.5, explosive: 0.4 },
    goldReward: 12,
    xpReward: 28,
    turretXpReward: 7,
    materialDropChance: 0.2,
    spawnCount: 2,
    spawnYOffset: 44,
    color: '#78350f',
    borderColor: '#f59e0b',
    baseDamage: 18,
  },
  {
    id: 'leech',
    name: 'Void Leech',
    icon: '🦠',
    category: 'swarm',
    baseHp: 18,
    hpPerWave: 4,
    speed: 2.8,
    speedPerWave: 0.07,
    armor: 0,
    size: 20,
    weakTo: { fire: 2.0, laser: 1.5 },
    strongAgainst: { poison: 0.3, electric: 0.8 },
    goldReward: 4,
    xpReward: 10,
    turretXpReward: 2,
    materialDropChance: 0.12,
    spawnCount: 4,
    spawnYOffset: 30,
    color: '#166534',
    borderColor: '#4ade80',
    baseDamage: 7,
  },
];
