/** ADVANCED MATERIALS — rare/epic/legendary drops, required for high-level upgrades */
import { MaterialDef } from './types';

export const ADVANCED_MATERIALS: MaterialDef[] = [
  {
    id: 'plasma_core',
    name: 'Plasma Core',
    icon: '🔮',
    rarity: 'rare',
    category: 'energy',
    description: 'Supercharged energy core. Required for Lv.4+ module upgrades.',
    dropWeight: 18,
  },
  {
    id: 'void_shard',
    name: 'Void Shard',
    icon: '💠',
    rarity: 'rare',
    category: 'exotic',
    description: 'Crystallised void energy. Needed for exotic module upgrades.',
    dropWeight: 15,
  },
  {
    id: 'quantum_filament',
    name: 'Quantum Filament',
    icon: '🌀',
    rarity: 'epic',
    category: 'energy',
    description: 'Rare quantum-entangled wire. Used in turret prestige upgrades.',
    dropWeight: 7,
  },
  {
    id: 'titan_alloy',
    name: 'Titan Alloy',
    icon: '⚗️',
    rarity: 'epic',
    category: 'scrap',
    description: 'Near-indestructible metal alloy from boss enemies.',
    dropWeight: 6,
  },
  {
    id: 'stellar_fragment',
    name: 'Stellar Fragment',
    icon: '⭐',
    rarity: 'legendary',
    category: 'exotic',
    description: 'Condensed stellar matter. Required for legendary module upgrades.',
    dropWeight: 2,
  },
  {
    id: 'dark_matter_core',
    name: 'Dark Matter Core',
    icon: '🌑',
    rarity: 'legendary',
    category: 'exotic',
    description: 'Impossibly dense dark matter. Used only in the highest-tier upgrades.',
    dropWeight: 1,
  },
  {
    id: 'neural_matrix',
    name: 'Neural Matrix',
    icon: '🧠',
    rarity: 'rare',
    category: 'bio',
    description: 'Harvested neural network from elite bio-enemies.',
    dropWeight: 14,
  },
  {
    id: 'cryo_crystal',
    name: 'Cryo Crystal',
    icon: '❄️',
    rarity: 'rare',
    category: 'exotic',
    description: 'Extremely cold crystal that stabilises energy systems.',
    dropWeight: 16,
  },
];
