/**
 * DAILY MISSIONS
 * 50 missions, each with a unique id, description, target, and reward.
 * Progress is tracked as current / target shown as "x/z".
 *
 * To add missions: extend the DAILY_MISSION_DEFS array.
 */

export interface MissionDef {
  id: string;
  title: string;
  description: string;
  /** Internal counter key used in play.tsx / store */
  counterKey: string;
  target: number;
  goldReward: number;
  xpReward: number;
  /** Optional material reward */
  materialReward?: { materialId: string; qty: number };
}

export const DAILY_MISSION_DEFS: MissionDef[] = [
  {
    id: 'd01',
    title: 'Bug Zapper',
    description: 'Kill Scout enemies',
    counterKey: 'kill_scout',
    target: 20,
    goldReward: 50,
    xpReward: 100,
  },
  {
    id: 'd02',
    title: 'Tank Buster',
    description: 'Kill Tank enemies',
    counterKey: 'kill_tank',
    target: 5,
    goldReward: 80,
    xpReward: 160,
  },
  {
    id: 'd03',
    title: 'Crowd Control',
    description: 'Kill Swarmers',
    counterKey: 'kill_swarmer',
    target: 40,
    goldReward: 60,
    xpReward: 120,
  },
  {
    id: 'd04',
    title: 'Bomb Disposal',
    description: 'Kill Bombers',
    counterKey: 'kill_bomber_swarm',
    target: 15,
    goldReward: 70,
    xpReward: 140,
  },
  {
    id: 'd05',
    title: 'Speed Demon',
    description: 'Kill Runners',
    counterKey: 'kill_runner',
    target: 25,
    goldReward: 55,
    xpReward: 110,
  },
  {
    id: 'd06',
    title: 'Shield Breaker',
    description: 'Kill Void Shielders',
    counterKey: 'kill_shielder',
    target: 8,
    goldReward: 90,
    xpReward: 180,
  },
  {
    id: 'd07',
    title: 'Giant Slayer',
    description: 'Kill Juggernauts',
    counterKey: 'kill_juggernaut',
    target: 3,
    goldReward: 120,
    xpReward: 240,
  },
  {
    id: 'd08',
    title: 'Elite Hunter',
    description: 'Kill Elite Commanders',
    counterKey: 'kill_elite',
    target: 2,
    goldReward: 150,
    xpReward: 300,
    materialReward: { materialId: 'plasma_core', qty: 2 },
  },
  {
    id: 'd09',
    title: 'Void Slayer',
    description: 'Kill Void Lords',
    counterKey: 'kill_void_lord',
    target: 1,
    goldReward: 250,
    xpReward: 500,
    materialReward: { materialId: 'void_shard', qty: 3 },
  },
  {
    id: 'd10',
    title: 'Parasite Purge',
    description: 'Kill Void Leeches',
    counterKey: 'kill_leech',
    target: 30,
    goldReward: 60,
    xpReward: 120,
  },
  {
    id: 'd11',
    title: 'Wave Rider',
    description: 'Survive 5 waves',
    counterKey: 'waves_survived',
    target: 5,
    goldReward: 80,
    xpReward: 160,
  },
  {
    id: 'd12',
    title: 'Endurance Test',
    description: 'Survive 10 waves',
    counterKey: 'waves_survived',
    target: 10,
    goldReward: 150,
    xpReward: 300,
  },
  {
    id: 'd13',
    title: 'War Machine',
    description: 'Survive 20 waves',
    counterKey: 'waves_survived',
    target: 20,
    goldReward: 300,
    xpReward: 600,
    materialReward: { materialId: 'titan_alloy', qty: 1 },
  },
  {
    id: 'd14',
    title: 'First Blood',
    description: 'Complete a run',
    counterKey: 'runs_completed',
    target: 1,
    goldReward: 50,
    xpReward: 100,
  },
  {
    id: 'd15',
    title: 'Veteran',
    description: 'Complete 3 runs',
    counterKey: 'runs_completed',
    target: 3,
    goldReward: 120,
    xpReward: 240,
  },
  {
    id: 'd16',
    title: 'Centurion',
    description: 'Kill 100 enemies total',
    counterKey: 'total_kills',
    target: 100,
    goldReward: 100,
    xpReward: 200,
  },
  {
    id: 'd17',
    title: 'Killmaster',
    description: 'Kill 500 enemies total',
    counterKey: 'total_kills',
    target: 500,
    goldReward: 250,
    xpReward: 500,
    materialReward: { materialId: 'plasma_core', qty: 3 },
  },
  {
    id: 'd18',
    title: 'Score Chaser',
    description: 'Reach 10,000 score',
    counterKey: 'high_score',
    target: 10000,
    goldReward: 100,
    xpReward: 200,
  },
  {
    id: 'd19',
    title: 'High Roller',
    description: 'Reach 50,000 score',
    counterKey: 'high_score',
    target: 50000,
    goldReward: 300,
    xpReward: 600,
    materialReward: { materialId: 'stellar_fragment', qty: 1 },
  },
  {
    id: 'd20',
    title: 'Gold Hoarder',
    description: 'Earn 500 gold total',
    counterKey: 'total_gold_earned',
    target: 500,
    goldReward: 100,
    xpReward: 100,
  },
  {
    id: 'd21',
    title: 'Turret Online',
    description: 'Unlock a turret in a run',
    counterKey: 'turrets_unlocked_run',
    target: 1,
    goldReward: 60,
    xpReward: 120,
  },
  {
    id: 'd22',
    title: 'Full Arsenal',
    description: 'Unlock all 4 turrets in one run',
    counterKey: 'turrets_unlocked_run',
    target: 4,
    goldReward: 200,
    xpReward: 400,
    materialReward: { materialId: 'quantum_filament', qty: 1 },
  },
  {
    id: 'd23',
    title: 'Power Play',
    description: 'Level up 5 times in a run',
    counterKey: 'run_level_ups',
    target: 5,
    goldReward: 80,
    xpReward: 160,
  },
  {
    id: 'd24',
    title: 'No Damage',
    description: 'Finish wave 3 without losing HP',
    counterKey: 'perfect_wave3',
    target: 1,
    goldReward: 150,
    xpReward: 300,
    materialReward: { materialId: 'cryo_crystal', qty: 2 },
  },
  {
    id: 'd25',
    title: 'Glass Hunter',
    description: 'Kill Glass Cannon enemies',
    counterKey: 'kill_glass_cannon',
    target: 10,
    goldReward: 75,
    xpReward: 150,
  },
  {
    id: 'd26',
    title: 'Scrap Collector',
    description: 'Collect 20 Iron Scrap',
    counterKey: 'mat_iron_scrap',
    target: 20,
    goldReward: 40,
    xpReward: 80,
  },
  {
    id: 'd27',
    title: 'Energized',
    description: 'Collect 10 Energy Cells',
    counterKey: 'mat_energy_cell',
    target: 10,
    goldReward: 50,
    xpReward: 100,
  },
  {
    id: 'd28',
    title: 'Rare Find',
    description: 'Collect a Plasma Core',
    counterKey: 'mat_plasma_core',
    target: 1,
    goldReward: 100,
    xpReward: 200,
    materialReward: { materialId: 'plasma_core', qty: 1 },
  },
  {
    id: 'd29',
    title: 'Void Walker',
    description: 'Collect a Void Shard',
    counterKey: 'mat_void_shard',
    target: 1,
    goldReward: 120,
    xpReward: 240,
    materialReward: { materialId: 'void_shard', qty: 1 },
  },
  {
    id: 'd30',
    title: 'Run Level 5',
    description: 'Reach run level 5',
    counterKey: 'run_level_reached',
    target: 5,
    goldReward: 80,
    xpReward: 160,
  },
  {
    id: 'd31',
    title: 'Run Level 10',
    description: 'Reach run level 10',
    counterKey: 'run_level_reached',
    target: 10,
    goldReward: 150,
    xpReward: 300,
    materialReward: { materialId: 'neural_matrix', qty: 1 },
  },
  {
    id: 'd32',
    title: 'Speedrun',
    description: 'Survive wave 5 without dying',
    counterKey: 'survive_wave5_nodeath',
    target: 1,
    goldReward: 100,
    xpReward: 200,
  },
  {
    id: 'd33',
    title: 'Chain Lightning',
    description: 'Deploy Tesla turret',
    counterKey: 'tesla_deployed',
    target: 1,
    goldReward: 60,
    xpReward: 120,
  },
  {
    id: 'd34',
    title: 'Missile Command',
    description: 'Deploy Missile turret',
    counterKey: 'missile_deployed',
    target: 1,
    goldReward: 60,
    xpReward: 120,
  },
  {
    id: 'd35',
    title: 'Laser Focus',
    description: 'Deploy Laser turret',
    counterKey: 'laser_deployed',
    target: 1,
    goldReward: 60,
    xpReward: 120,
  },
  {
    id: 'd36',
    title: 'Heavy Weapons',
    description: 'Deploy Cannon turret',
    counterKey: 'cannon_deployed',
    target: 1,
    goldReward: 60,
    xpReward: 120,
  },
  {
    id: 'd37',
    title: 'Level Up!',
    description: 'Reach commander level 2',
    counterKey: 'char_level',
    target: 2,
    goldReward: 50,
    xpReward: 100,
  },
  {
    id: 'd38',
    title: 'Commander',
    description: 'Reach commander level 5',
    counterKey: 'char_level',
    target: 5,
    goldReward: 150,
    xpReward: 300,
    materialReward: { materialId: 'titan_alloy', qty: 1 },
  },
  {
    id: 'd39',
    title: 'Module Mastery',
    description: 'Upgrade any module',
    counterKey: 'modules_upgraded',
    target: 1,
    goldReward: 40,
    xpReward: 80,
  },
  {
    id: 'd40',
    title: 'Mod Tech',
    description: 'Upgrade 5 modules total',
    counterKey: 'modules_upgraded',
    target: 5,
    goldReward: 100,
    xpReward: 200,
    materialReward: { materialId: 'cryo_crystal', qty: 2 },
  },
  {
    id: 'd41',
    title: 'Run Streak',
    description: 'Complete 2 runs in a day',
    counterKey: 'daily_runs',
    target: 2,
    goldReward: 80,
    xpReward: 160,
  },
  {
    id: 'd42',
    title: 'Triple Threat',
    description: 'Complete 3 runs in a day',
    counterKey: 'daily_runs',
    target: 3,
    goldReward: 150,
    xpReward: 300,
    materialReward: { materialId: 'plasma_core', qty: 2 },
  },
  {
    id: 'd43',
    title: 'Titan Slayer',
    description: 'Kill Corrupted Titan',
    counterKey: 'kill_corrupted_titan',
    target: 1,
    goldReward: 400,
    xpReward: 800,
    materialReward: { materialId: 'dark_matter_core', qty: 1 },
  },
  {
    id: 'd44',
    title: 'Iron Will',
    description: 'Survive a run with under 10 HP',
    counterKey: 'close_call_survive',
    target: 1,
    goldReward: 120,
    xpReward: 240,
    materialReward: { materialId: 'neural_matrix', qty: 2 },
  },
  {
    id: 'd45',
    title: 'Rapid Fire',
    description: 'Kill 10 enemies in 30 seconds',
    counterKey: 'rapid_kills',
    target: 10,
    goldReward: 70,
    xpReward: 140,
  },
  {
    id: 'd46',
    title: 'Untouchable',
    description: 'Survive wave 7 without dying',
    counterKey: 'survive_wave7_nodeath',
    target: 1,
    goldReward: 180,
    xpReward: 360,
    materialReward: { materialId: 'void_shard', qty: 2 },
  },
  {
    id: 'd47',
    title: 'Armour Piercer',
    description: 'Kill 5 Juggernauts',
    counterKey: 'kill_juggernaut',
    target: 5,
    goldReward: 200,
    xpReward: 400,
    materialReward: { materialId: 'titan_alloy', qty: 2 },
  },
  {
    id: 'd48',
    title: 'Double Prestige',
    description: 'Reach Prestige 2',
    counterKey: 'prestige_level',
    target: 2,
    goldReward: 300,
    xpReward: 600,
    materialReward: { materialId: 'stellar_fragment', qty: 2 },
  },
  {
    id: 'd49',
    title: 'Domination',
    description: 'Kill 1000 enemies total',
    counterKey: 'total_kills',
    target: 1000,
    goldReward: 500,
    xpReward: 1000,
    materialReward: { materialId: 'dark_matter_core', qty: 1 },
  },
  {
    id: 'd50',
    title: 'Legend',
    description: 'Survive 50 waves across all runs',
    counterKey: 'total_waves',
    target: 50,
    goldReward: 400,
    xpReward: 800,
    materialReward: { materialId: 'stellar_fragment', qty: 3 },
  },
];

/** Map for quick lookup */
export const MISSION_MAP: Record<string, MissionDef> = Object.fromEntries(
  DAILY_MISSION_DEFS.map((m) => [m.id, m])
);
